# Generated by Django 5.1 on 2024-12-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва матеріалу')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис матеріалу')),
                ('material_type', models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('video', 'YouTube Video'), ('link', 'Link')], max_length=10, verbose_name='Тип матеріалу')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/files/', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/images/', verbose_name='Зображення')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Посилання на YouTube')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Зовнішнє посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Додав користувач')),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
                'ordering': ['-created_at'],
            },
        ),
    ]
