# Generated by Django 5.1 on 2024-12-11 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Матеріал', 'verbose_name_plural': 'Матеріали'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='material',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='material',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Посилання'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Опис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('file', 'Файл'), ('image', 'Зображення'), ('youtube', 'YouTube Посилання'), ('link', 'Посилання')], max_length=10, verbose_name='Тип матеріалу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
    ]
