# Generated by Django 5.1.3 on 2024-12-27 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Відео')], max_length=10, verbose_name='Тип')),
                ('file', models.FileField(upload_to='gallery/', verbose_name='Файл')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Перевірено')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Завантажив')),
            ],
        ),
    ]
